// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDrb1FI5kFHsYARFh-XoBbbmXeVfzCOOo',
    appId: '1:768796824422:android:1482f0528f5337af366ea7',
    messagingSenderId: '768796824422',
    projectId: 'presbiteriana-renovada-app',
    databaseURL: 'https://presbiteriana-renovada-app-default-rtdb.firebaseio.com',
    storageBucket: 'presbiteriana-renovada-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDLIMsg4TTbLcYa_kW6k5ZeIwFEG5pex8',
    appId: '1:768796824422:ios:0ec37a71f100329f366ea7',
    messagingSenderId: '768796824422',
    projectId: 'presbiteriana-renovada-app',
    databaseURL: 'https://presbiteriana-renovada-app-default-rtdb.firebaseio.com',
    storageBucket: 'presbiteriana-renovada-app.appspot.com',
    iosClientId: '768796824422-lt85osfnpfm48itfoirefsgpjmj1suke.apps.googleusercontent.com',
    iosBundleId: 'com.example.presbiterianaRenovadaApp',
  );
}
